#!/bin/bash

. common

rsync -e ssh -c -h -L --progress --partial ftparchlinux@depot.kde.org:${branch}/frameworks/${kdever%.*}/*.xz ${SRCDEST}/
rsync -e ssh -c -h -L --progress --partial ftparchlinux@depot.kde.org:${branch}/frameworks/${kdever%.*}/portingAids/*.xz ${SRCDEST}/
